#!/bin/sh

if [ "$#" -ne 1 ]
then
  echo "Usage: Must supply a domain"
  exit 1
fi

if [ ! -f CA/TinyCA.key ] || [ ! -f CA/TinyCA.pem ]; then
    echo "TinyCA is not generated yet, please run gen_CA.sh and make a TinyCA!"
    exit 1
fi

DOMAIN=$1

cd Sites
mkdir $DOMAIN
cd $DOMAIN

openssl genrsa -out $DOMAIN.key 2048
openssl req -new -key $DOMAIN.key -out $DOMAIN.csr

cat > $DOMAIN.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = $DOMAIN
EOF

openssl x509 -req -in $DOMAIN.csr -CA ../../CA/TinyCA.pem -CAkey ../../CA/TinyCA.key -CAcreateserial \
-out $DOMAIN.crt -days 825 -sha256 -extfile $DOMAIN.ext

echo "\nTinyCA has created a new certificate for your site - $DOMAIN !"
echo "\nFiles generated by TinyCA (./Sites/$DOMAIN);"
ls